### ISSUE TITLE
Error creating session record (epoch.tags)

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_sessions#128]
affects: 
- `703882_2024-04-24`
- `708016_2024-05-02`
- `706401_2024-04-22`

```
2024-09-20 14:42:22 | __main__ | WARNING | Missing metadata record for 706401_2024-04-22:
Traceback (most recent call last):
  File "/code/npc_sessions_cache/src/npc_sessions_cache/utils/session_records.py", line 322, in write_session_record
    store[key] = get_session_record(session_id, session=session)
  File "/code/npc_sessions_cache/src/npc_sessions_cache/utils/session_records.py", line 282, in get_session_record
    is_timing_issues="timing_issues" in epochs.tags.explode().unique(),
AttributeError: 'list' object has no attribute 'tags'
```

**Comment by bjhardcastle** [comment]
Verified this is fixed
