### ISSUE TITLE
Error getting units for `644864_2023-02-02`

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_sessions#129]
Might be related to #126 

```
2024-09-20 14:42:22 | __main__ | WARNING | Missing metadata record for 644864_2023-02-02:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/npc_sessions_cache/utils/session_records.py", line 321, in write_session_record
    store[key] = get_session_record(session_id)
  File "/opt/conda/lib/python3.9/site-packages/npc_sessions_cache/utils/session_records.py", line 238, in get_session_record
    units = session.units[:]
  File "/opt/conda/lib/python3.9/site-packages/npc_io/cached_property.py", line 78, in __get__
    val = self.func(instance)
  File "/src/npc-sessions/src/npc_sessions/sessions.py", line 1468, in units
    for column in self._units.columns:
  File "/opt/conda/lib/python3.9/site-packages/npc_io/cached_property.py", line 78, in __get__
    val = self.func(instance)
  File "/src/npc-sessions/src/npc_sessions/sessions.py", line 1405, in _units
    units=npc_ephys.make_units_table_from_spike_interface_ks25(
  File "/opt/conda/lib/python3.9/site-packages/npc_ephys/units.py", line 277, in make_units_table_from_spike_interface_ks25
    raise e from None
  File "/opt/conda/lib/python3.9/site-packages/npc_ephys/units.py", line 269, in make_units_table_from_spike_interface_ks25
    _ = future.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.9/site-packages/npc_ephys/units.py", line 184, in _device_helper
    assert np.array_equal(
AssertionError: cluster-ids from npy file do not match index column in metrics.csv
```

**Comment by bjhardcastle** [comment]
This turned out to be some missing or unreadable npy files in the sorted data asset.

Re-sorted, but the output is different and cannot currently integrate (see #135)
