### ISSUE TITLE
Fix issue reading newscale csv logs

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_sessions#131]
affects these sessions (`id`, `name`, `created` refer to computation results from write-cache capsule):
```
shape: (4, 7)
┌───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬────────────┬─────────┐
│ session_id    ┆ error        ┆ name         ┆ id           ┆ created      ┆ has_issues ┆ is_prod │
│ ---           ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---        ┆ ---     │
│ str           ┆ str          ┆ str          ┆ str          ┆ str          ┆ i64        ┆ i64     │
╞═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪════════════╪═════════╡
│ 736208_2024-0 ┆ Original     ┆ Run With     ┆ 21453fcc-610 ┆ 2024-09-21T0 ┆ 0          ┆ 1       │
│ 9-05          ┆ error:       ┆ Parameters   ┆ 3-4c7e-9f16- ┆ 1:12:48      ┆            ┆         │
│               ┆ ```could not ┆ 6881168      ┆ 169513…      ┆              ┆            ┆         │
│               ┆ p…           ┆              ┆              ┆              ┆            ┆         │
│ 736208_2024-0 ┆ Original     ┆ Run With     ┆ 42742274-35d ┆ 2024-09-21T0 ┆ 0          ┆ 1       │
│ 9-04          ┆ error:       ┆ Parameters   ┆ 9-4fd3-aaf4- ┆ 1:13:12      ┆            ┆         │
│               ┆ ```could not ┆ 6881192      ┆ fc0adf…      ┆              ┆            ┆         │
│               ┆ p…           ┆              ┆              ┆              ┆            ┆         │
│ 736208_2024-0 ┆ Original     ┆ Run With     ┆ a734e322-79d ┆ 2024-09-21T0 ┆ 0          ┆ 1       │
│ 9-03          ┆ error:       ┆ Parameters   ┆ 2-4eb3-bf76- ┆ 1:13:35      ┆            ┆         │
│               ┆ ```could not ┆ 6881215      ┆ 078f9f…      ┆              ┆            ┆         │
│               ┆ p…           ┆              ┆              ┆              ┆            ┆         │
│ 715709_2024-0 ┆ Original     ┆ Run With     ┆ c529311f-ef0 ┆ 2024-09-21T0 ┆ 0          ┆ 0       │
│ 8-09          ┆ error:       ┆ Parameters   ┆ 8-40a0-80da- ┆ 1:16:35      ┆            ┆         │
│               ┆ ```could not ┆ 6881395      ┆ c0db43…      ┆              ┆            ┆         │
│               ┆ p…           ┆              ┆              ┆              ┆            ┆         │
└───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴────────────┴─────────┘
```

traceback:
```
Traceback (most recent call last):

  File "/code/run.py", line 55, in <module>
    npc_sessions_cache.write_all_components_to_cache(session=session, skip_existing=args.skip_existing)
  File "/code/npc_sessions_cache/src/npc_sessions_cache/utils/cache.py", line 251, in write_all_components_to_cache
    component = _get_nwb_component(session, component_name)
  File "/code/npc_sessions_cache/src/npc_sessions_cache/utils/cache.py", line 98, in _get_nwb_component
    c = getattr(session, component_name, None)
  File "/opt/conda/lib/python3.9/site-packages/npc_io/cached_property.py", line 79, in __get__
    val = self.func(instance)
  File "/opt/conda/lib/python3.9/site-packages/npc_sessions/sessions.py", line 1325, in devices
    for module in self._devices:
  File "/opt/conda/lib/python3.9/site-packages/npc_sessions/sessions.py", line 1314, in _devices
    devices.extend(self._manipulators)
  File "/opt/conda/lib/python3.9/site-packages/npc_io/cached_property.py", line 79, in __get__
    val = self.func(instance)
  File "/opt/conda/lib/python3.9/site-packages/npc_sessions/sessions.py", line 1291, in _manipulators
    _ = self._manipulator_positions
  File "/opt/conda/lib/python3.9/site-packages/npc_io/cached_property.py", line 79, in __get__
    val = self.func(instance)
  File "/opt/conda/lib/python3.9/site-packages/npc_sessions/sessions.py", line 2140, in _manipulator_positions
    df = npc_ephys.get_newscale_coordinates(
  File "/opt/conda/lib/python3.9/site-packages/npc_ephys/newscale.py", line 114, in get_newscale_coordinates
    df = get_newscale_data(newscale_log_path)
  File "/opt/conda/lib/python3.9/site-packages/npc_ephys/newscale.py", line 76, in get_newscale_data
    return pl.read_csv(
  File "/opt/conda/lib/python3.9/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/polars/io/csv/functions.py", line 500, in read_csv
    df = _read_csv_impl(
  File "/opt/conda/lib/python3.9/site-packages/polars/io/csv/functions.py", line 646, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
polars.exceptions.ComputeError: could not parse `2024/08/09 10:25:54.907` as dtype `datetime[μs]` at column '2024/07/02 13:57:40.559' (column number 1)

The current offset in the file is 3425782 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `2024/08/09 10:25:54.907` to the `null_values` list.

Original error: ```could not parse '2024/08/09 10:25:54.907' with pattern 'DatetimeYMD'```

```

**Comment by bjhardcastle** [comment]
Caused by log files with null values at start of date column:

```csv
2024/08/09 10:20:40.732, SN45485, 8911.5, 5519.5, 5567.5, 8911.5, 5519.5, 5567.5
2024/08/09 10:20:40.802, SN45356, 9068.5, 8236.0, 4235.5, 9068.5, 8236.0, 4235.5
nullnulnullnull ... 2024/08/09 10:25:54.907, SN45485, 8911.5, 5520.0, 5558.5, 8911.5, 5520.0, 5558.5
2024/08/09 10:25:55.447, SN45485, 8911.5, 5520.0, 5556.5, 8911.5, 5520.0, 5556.5
```
