### ISSUE TITLE
Fix `"Exception: could not resolve dtype for VectorData 'spike_times'"`

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_sessions#132]
affected sessions:
```
shape: (2, 8)
┌───────────────────┬───────────────────────┬───────────────────────┬───────────────────────┬─────────────────────┬────────────┬─────────┬────────────────┐
│ session_id        ┆ error                 ┆ name                  ┆ id                    ┆ created             ┆ has_issues ┆ is_prod ┆ error_priority │
│ ---               ┆ ---                   ┆ ---                   ┆ ---                   ┆ ---                 ┆ ---        ┆ ---     ┆ ---            │
│ str               ┆ str                   ┆ str                   ┆ str                   ┆ str                 ┆ i64        ┆ i64     ┆ i64            │
╞═══════════════════╪═══════════════════════╪═══════════════════════╪═══════════════════════╪═════════════════════╪════════════╪═════════╪════════════════╡
│ 666986_2023-08-15 ┆ Exception: could not… ┆ Run With Parameters … ┆ 7f56de9e-6c9a-42a8-b… ┆ 2024-09-21T01:41:09 ┆ 0          ┆ 1       ┆ 2              │
│ 708016_2024-05-01 ┆ Exception: could not… ┆ Run With Parameters … ┆ 949bb6ed-c4ad-476b-b… ┆ 2024-09-21T01:26:57 ┆ 0          ┆ 1       ┆ 2              │
└───────────────────┴───────────────────────┴───────────────────────┴───────────────────────┴─────────────────────┴────────────┴─────────┴────────────────┘
```

```
Traceback (most recent call last):

  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 782, in build
    bldr_data, dtype = self.convert_dtype(spec, data, spec_dtype=spec_dtype)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 238, in convert_dtype
    ret = type(value)(ret)
MemoryError

The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/code/run.py", line 52, in <module>
    npc_sessions_cache.write_and_upload_session_nwb(session=session, skip_existing=args.skip_existing, zarr=False)
  File "/code/npc_sessions_cache/src/npc_sessions_cache/utils/cache.py", line 213, in write_and_upload_session_nwb
    tmpfile = session.write_nwb(path=tmpfile, metadata_only=metadata_only, zarr=zarr)
  File "/opt/conda/lib/python3.9/site-packages/npc_sessions/sessions.py", line 383, in write_nwb
    io.write(nwb)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py", line 395, in write
    super().write(**kwargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/backends/io.py", line 98, in write
    f_builder = self.__manager.build(container, source=self.__source, root=True)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/manager.py", line 173, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext, export=export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/manager.py", line 789, in build
    builder = obj_mapper.build(container, manager, builder=builder, source=source, spec_ext=spec_ext, export=export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 718, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source, export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1137, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container, export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1157, in __add_containers
    new_builder = build_manager.build(value, source=source, spec_ext=spec, export=export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/manager.py", line 173, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext, export=export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/manager.py", line 789, in build
    builder = obj_mapper.build(container, manager, builder=builder, source=source, spec_ext=spec_ext, export=export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 717, in build
    self.__add_datasets(builder, self.__spec.datasets, container, manager, source, export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1107, in __add_datasets
    self.__add_containers(builder, spec, attr_value, build_manager, source, container, export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1157, in __add_containers
    new_builder = build_manager.build(value, source=source, spec_ext=spec, export=export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/manager.py", line 173, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext, export=export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/manager.py", line 789, in build
    builder = obj_mapper.build(container, manager, builder=builder, source=source, spec_ext=spec_ext, export=export)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 785, in build
    raise Exception(msg) from ex
Exception: could not resolve dtype for VectorData 'spike_times'
```

**Comment by bjhardcastle** [comment]
- `nwb.units.spike_times` appear normal in memory
- we've previously written both sessions to NWB
- `MemoryError` suggests we just ran out of memory in the capsule

Will increase the RAM on the machine used for caching.
