### ISSUE TITLE
Make dlc `PoseEstimationSeries` a `DynamicTable`

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/npc_sessions#137]
It's much easier to use.. 

Q: Does it make it any more difficult to compress data as a table?

**Comment by bjhardcastle** [comment]
Let's put this on hold for now - we may not use the side/body DLC anyway.

**Comment by bjhardcastle** [comment]
This started crashing so I'm inclined to switch instead of fixing the issue (the message says it's supposedly a warning, but it actually raises an exception):

```python
Traceback (most recent call last):
  File "/code/run.py", line 61, in <module>
    npc_sessions_cache.write_all_components_to_cache(session=session, skip_existing=args.skip_existing)
  File "/code/npc_sessions_cache/src/npc_sessions_cache/utils/cache.py", line 260, in write_all_components_to_cache
    component = _get_nwb_component(session, component_name)
  File "/code/npc_sessions_cache/src/npc_sessions_cache/utils/cache.py", line 92, in _get_nwb_component
    in session.processing["behavior"].fields["data_interfaces"].keys()
  File "/opt/conda/lib/python3.9/site-packages/npc_sessions/sessions.py", line 751, in processing
    module = getattr(self, f"_{module_name}")
  File "/opt/conda/lib/python3.9/site-packages/npc_io/cached_property.py", line 79, in __get__
    val = self.func(instance)
  File "/opt/conda/lib/python3.9/site-packages/npc_sessions/sessions.py", line 776, in _behavior
    modules.extend(self._dlc)
  File "/opt/conda/lib/python3.9/site-packages/npc_io/cached_property.py", line 79, in __get__
    val = self.func(instance)
  File "/opt/conda/lib/python3.9/site-packages/npc_sessions/sessions.py", line 3100, in _dlc
    ndx_pose.pose.PoseEstimation(
  File "/opt/conda/lib/python3.9/site-packages/hdmf/utils.py", line 668, in func_call
    return func(args[0], **pargs)
  File "/opt/conda/lib/python3.9/site-packages/ndx_pose/pose.py", line 268, in __init__
    raise DeprecationWarning(msg)
DeprecationWarning: The number of original videos must equal the number of camera devices. This will become an error in a future release.
```

**Comment by arjunsridhar12345** [comment]
yeah sounds good. i guess we just keep it for now then with the switch? (or not use the dlc at all since I don't think its used in the analysis anywhere)
